* SimpleMUD
  :PROPERTIES:
  :CUSTOM_ID: simplemud
  :END:

As its name implies, SimpleMUD is a NodeJS implementation of a
rudimentary MUD server. It is intended to be used as a learning
experience for those who has never programmed a MUD server before.

The original codebase for SimpleMUD was written in C++ by Ron Penton,
the author of /MUD Game Programming/ book.

** Demo
   :PROPERTIES:
   :CUSTOM_ID: demo
   :END:

WebTelnet: http://smud.ourmmo.com

Telnet: smud.ourmmo.com 3000

** Highlights
   :PROPERTIES:
   :CUSTOM_ID: highlights
   :END:

- Physical data (Items, Players, Rooms, Enemy Templates) are stored in
  JSON files
- Dynamic game data (Timers, Enemies, Room's Loots) are also stored in
  JSON files
- Every major functionality is fully unit-tested (189 total test cases)
- Total lines of code for implementation is 2265
- Total lines of code for unit tests is 3032

** Requirements
   :PROPERTIES:
   :CUSTOM_ID: requirements
   :END:

- Node.js >= v6.4.0

** To Run Server
   :PROPERTIES:
   :CUSTOM_ID: to-run-server
   :END:

#+BEGIN_EXAMPLE
    $ git clone https://github.com/lnguyenfx/simplemud.git
    $ cd simplemud
    $ npm install
    $ npm start <port>
#+END_EXAMPLE

** To Run Client
   :PROPERTIES:
   :CUSTOM_ID: to-run-client
   :END:

#+BEGIN_EXAMPLE
    $ telnet localhost <port>
#+END_EXAMPLE

** To Execute Tests
   :PROPERTIES:
   :CUSTOM_ID: to-execute-tests
   :END:

All tests:

#+BEGIN_EXAMPLE
    $ npm test
#+END_EXAMPLE

Individual test:

#+BEGIN_EXAMPLE
    $npm test "test/<ClassName>.js"
#+END_EXAMPLE

** Special Thanks
   :PROPERTIES:
   :CUSTOM_ID: special-thanks
   :END:

Ron Penton for the original SimpleMUD C++ codebase.

Shawn Biddle for [[http://ranviermud.com][RanvierMUD]], which is a
source of inspirations.

Raymond Xie for the [[https://github.com/mudchina/webtelnet][WebTelnet]]
that is used as the Demo.

** License
   :PROPERTIES:
   :CUSTOM_ID: license
   :END:

Copyright (c) 2017, Long Nguyen
[[mailto:lnguyenfx@gmail.com][lnguyenfx@gmail.com]]

Licensed under the [[../master/LICENSE.txt][MIT License]]
